In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

In [12]:
data=pd.read_csv("train.csv")

In [13]:
data_backup=data.copy()


In [14]:
data.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [15]:
data.shape

(13320, 9)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB



since there were inconisitency in the dataset in the beds column, we are replacinig Bedrooms with BHK

In [17]:
import re
data['size'] = data['size'].apply(lambda x: re.sub(r'\bBedroom\b', 'BHK', x, flags=re.IGNORECASE) if isinstance(x, str) else x)

In [18]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...  
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                 540
Sarjapur  Road             399
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ... 
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK     5528
3 BHK     4857
4 BHK     1417
1 BHK      643
5 BHK      356
6 BHK      

In [19]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [20]:
data.head()


area_type   availability                  location   size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II  2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 BHK   
2        Built-up  Area  Ready To Move               Uttarahalli  3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli  3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur  2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

removing columns from the dataset which is only required for this project

In [21]:
data.drop(columns=['availability','society'],inplace=True)

In [22]:
data.head()

area_type                  location   size total_sqft  bath  \
0  Super built-up  Area  Electronic City Phase II  2 BHK       1056   2.0   
1            Plot  Area          Chikka Tirupathi  4 BHK       2600   5.0   
2        Built-up  Area               Uttarahalli  3 BHK       1440   2.0   
3  Super built-up  Area        Lingadheeranahalli  3 BHK       1521   3.0   
4  Super built-up  Area                  Kothanur  2 BHK       1200   2.0   

   balcony   price  
0      1.0   39.07  
1      3.0  120.00  
2      3.0   62.00  
3      1.0   95.00  
4      1.0   51.00

In [23]:
data.isna().sum()

area_type       0
location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [24]:
data.rename(columns={'size': 'beds','total_sqft':'size_sqft'}, inplace=True)

In [25]:
data.head()

area_type                  location   beds size_sqft  bath  \
0  Super built-up  Area  Electronic City Phase II  2 BHK      1056   2.0   
1            Plot  Area          Chikka Tirupathi  4 BHK      2600   5.0   
2        Built-up  Area               Uttarahalli  3 BHK      1440   2.0   
3  Super built-up  Area        Lingadheeranahalli  3 BHK      1521   3.0   
4  Super built-up  Area                  Kothanur  2 BHK      1200   2.0   

   balcony   price  
0      1.0   39.07  
1      3.0  120.00  
2      3.0   62.00  
3      1.0   95.00  
4      1.0   51.00

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   area_type  13320 non-null  object 
 1   location   13319 non-null  object 
 2   beds       13304 non-null  object 
 3   size_sqft  13320 non-null  object 
 4   bath       13247 non-null  float64
 5   balcony    12711 non-null  float64
 6   price      13320 non-null  float64
dtypes: float64(3), object(4)
memory usage: 728.6+ KB


coverting values in price to be more understandable

In [27]:
data['price'] = data['price'].apply(lambda x: x * 1000 if isinstance(x, (int, float)) else x)

In [28]:
data.head(20)

area_type                  location   beds size_sqft  bath  \
0   Super built-up  Area  Electronic City Phase II  2 BHK      1056   2.0   
1             Plot  Area          Chikka Tirupathi  4 BHK      2600   5.0   
2         Built-up  Area               Uttarahalli  3 BHK      1440   2.0   
3   Super built-up  Area        Lingadheeranahalli  3 BHK      1521   3.0   
4   Super built-up  Area                  Kothanur  2 BHK      1200   2.0   
5   Super built-up  Area                Whitefield  2 BHK      1170   2.0   
6   Super built-up  Area          Old Airport Road  4 BHK      2732   4.0   
7   Super built-up  Area              Rajaji Nagar  4 BHK      3300   4.0   
8   Super built-up  Area              Marathahalli  3 BHK      1310   3.0   
9             Plot  Area              Gandhi Bazar  6 BHK      1020   6.0   
10  Super built-up  Area                Whitefield  3 BHK      1800   2.0   
11            Plot  Area                Whitefield  4 BHK      2785   5.0   
12  Super built-up  Area        7th Phase JP Nagar  2 BHK      1000   2.0   
13        Built-up  Area                 Gottigere  2 BHK      1100   2.0   
14            Plot  Area                  Sarjapur  3 BHK      2250   3.0   
15  Super built-up  Area               Mysore Road  2 BHK      1175   2.0   
16  Super built-up  Area             Bisuvanahalli  3 BHK      1180   3.0   
17  Super built-up  Area     Raja Rajeshwari Nagar  3 BHK      1540   3.0   
18  Super built-up  Area     Ramakrishnappa Layout  3 BHK      2770   4.0   
19  Super built-up  Area        Manayata Tech Park  2 BHK      1100   2.0   

    balcony     price  
0       1.0   39070.0  
1       3.0  120000.0  
2       3.0   62000.0  
3       1.0   95000.0  
4       1.0   51000.0  
5       1.0   38000.0  
6       NaN  204000.0  
7       NaN  600000.0  
8       1.0   63250.0  
9       NaN  370000.0  
10      2.0   70000.0  
11      3.0  295000.0  
12      1.0   38000.0  
13      2.0   40000.0  
14      2.0  148000.0  
15      2.0   73500.0  
16      2.0   48000.0  
17      3.0   60000.0  
18      2.0  290000.0  
19      2.0   48000.0

In [29]:
data.drop(columns=['area_type'],inplace=True)

In [30]:
data.head()

location   beds size_sqft  bath  balcony     price
0  Electronic City Phase II  2 BHK      1056   2.0      1.0   39070.0
1          Chikka Tirupathi  4 BHK      2600   5.0      3.0  120000.0
2               Uttarahalli  3 BHK      1440   2.0      3.0   62000.0
3        Lingadheeranahalli  3 BHK      1521   3.0      1.0   95000.0
4                  Kothanur  2 BHK      1200   2.0      1.0   51000.0

In [31]:
def convert_size(size):
    if isinstance(size, str):
        # Remove non-numeric characters except for '-' and '.'
        size = re.sub(r'[^\d.-]', '', size).rstrip('.')
        if '-' in size:
            parts = size.split('-')
            try:
                return (float(parts[0]) + float(parts[1])) / 2
            except ValueError:
                return np.nan
        try:
            return float(size)
        except ValueError:
            return np.nan
    return size

In [32]:
data['size_sqft'] = data['size_sqft'].apply(convert_size)

saving the new dataset

In [33]:
data.columns


Index(['location', 'beds', 'size_sqft', 'bath', 'balcony', 'price'], dtype='object')

In [34]:
data.head()

location   beds  size_sqft  bath  balcony     price
0  Electronic City Phase II  2 BHK     1056.0   2.0      1.0   39070.0
1          Chikka Tirupathi  4 BHK     2600.0   5.0      3.0  120000.0
2               Uttarahalli  3 BHK     1440.0   2.0      3.0   62000.0
3        Lingadheeranahalli  3 BHK     1521.0   3.0      1.0   95000.0
4                  Kothanur  2 BHK     1200.0   2.0      1.0   51000.0

In [35]:
data['beds'] = data['beds'].astype(str)

In [36]:
data.to_csv("final_dataset.csv")

In [37]:
data.shape

(13320, 6)

In [38]:
X=data.drop(columns=['price'])
Y=data['price']

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score

In [40]:
# data['bath'].fillna(data['bath'].median(), inplace=True)
# data['balcony'].fillna(data['balcony'].median(), inplace=True)
# data['location'].fillna(data['location'].mode()[0], inplace=True)
# data['beds'].fillna(data['beds'].mode()[0],inplace=True)

data['bath'] = data['bath'].median()
data['balcony']=data['balcony'].median()
data['location']=data['location'].mode()[0]
data['beds']=data['beds'].mode()[0]

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   location   13320 non-null  object 
 1   beds       13320 non-null  object 
 2   size_sqft  13320 non-null  float64
 3   bath       13320 non-null  float64
 4   balcony    13320 non-null  float64
 5   price      13320 non-null  float64
dtypes: float64(4), object(2)
memory usage: 624.5+ KB


In [42]:
numerical_cols = ['bath', 'balcony', 'size_sqft']
categorical_cols = ['location', 'beds']

In [43]:
column_trans = ColumnTransformer(
    transformers=[
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='median')),
              # ('scaler', StandardScaler())
        ]), numerical_cols),
        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_cols)
    ]
)

In [44]:
pipeline = Pipeline(steps=[
    ('preprocessor', column_trans),
    ('regressor', LinearRegression())
])

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


In [46]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['bath', 'balcony',
                                                   'size_sqft']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'beds'])])),
                ('regressor', LinearRegression())])

In [47]:
Y_pred_linear= pipeline.predict(X_test)

In [48]:
Y_pred_linear

array([ 10917.78098891,  63906.00943199,  80649.26417625, ...,
       105191.14503985,  56191.09128719, 103543.99511468])

In [49]:
r2_lin = r2_score(Y_test, Y_pred_linear)

In [50]:
print(f'R-squared score: {r2_lin}')

R-squared score: 0.5658057680647315


using lasso


In [51]:
lasso = Lasso(alpha=1.0, max_iter=10000)

In [52]:
pipeline = Pipeline(steps=[
    ('preprocessor', column_trans),
    ('regressor', lasso)
])

In [53]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['bath', 'balcony',
                                                   'size_sqft']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'beds'])])),
                ('regressor', Lasso(max_iter=10000))])

In [91]:
Y_pred_lasso= pipeline.predict(X_test)

In [92]:
Y_pred_lasso

array([ 12446.12456631,  65183.94312346,  80521.85593835, ...,
       106538.56104276,  56113.13588354, 103286.93586356])

In [57]:
r2_las = r2_score(Y_test, Y_pred_lasso)

In [58]:
print(f'R-squared score: {r2_las}')

R-squared score: 0.5659932442236322


using Ridge

In [59]:
ridge = Ridge()

In [60]:
pipeline = Pipeline(steps=[
    ('preprocessor', column_trans),
    ('regressor', lasso)
])

In [61]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['bath', 'balcony',
                                                   'size_sqft']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'beds'])])),
                ('regressor', Lasso(max_iter=10000))])

In [62]:
Y_pred_ridge= pipeline.predict(X_test)

In [63]:
Y_pred_ridge

array([ 12446.12456631,  65183.94312346,  80521.85593835, ...,
       106538.56104276,  56113.13588354, 103286.93586356])

In [ ]:
r2_rid = r2_score(Y_test, Y_pred_ridge)

In [ ]:
print(f'R-squared score: {r2_rid}')

In [ ]:
print("linearRig",r2_lin)
print("lasso",r2_las)
print("ridge",r2_rid)

In [66]:
import pickle

In [ ]:
pickle.dump(pipeline, open('ridgemodel.pkl','wb'))

random forest regression

In [54]:
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators = 10, random_state = 0)

In [55]:
pipeline = Pipeline(steps=[
    ('preprocessor', column_trans),
    ('regressor', rf_model)
])

In [56]:
pipeline.fit(X_train, Y_train) 


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['bath', 'balcony',
                                                   'size_sqft']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'beds'])])),
                ('regressor',
                 RandomForestRegressor(n_estimators=10, random_state=0))])

In [57]:
Y_pred_rf= pipeline.predict(X_test)

In [58]:
X_test

location   beds  size_sqft  bath  balcony
8077   Banjara Layout  2 BHK     1050.0   2.0      1.0
1602      Rajiv Nagar  3 BHK     1690.0   3.0      1.0
10498          Hebbal  2 BHK     1100.0   2.0      1.0
3297      Munnekollal  6 BHK     1200.0   4.0      2.0
8893     Choodasandra  4 BHK     2429.0   3.0      1.0
...               ...    ...        ...   ...      ...
1082     Ananth Nagar  1 BHK      500.0   1.0      1.0
1671        Herohalli  5 BHK     1800.0   6.0      0.0
4325      AECS Layout  3 BHK     1800.0   3.0      3.0
7375   Vinayaka Nagar  2 BHK     1200.0   2.0      2.0
5152       R.T. Nagar  3 BHK     1140.0   3.0      1.0

[2664 rows x 5 columns]

In [59]:
Y_test

8077      64800.0
1602     125000.0
10498     60000.0
3297     110000.0
8893     210000.0
           ...   
1082      14000.0
1671      44500.0
4325      65000.0
7375      52000.0
5152     130000.0
Name: price, Length: 2664, dtype: float64

In [60]:
X_train

location   beds  size_sqft  bath  balcony
3411      Lingadheeranahalli  3 BHK     1530.0   2.0      2.0
9142              Cooke Town  2 BHK     1310.0   2.0      2.0
1971   Raja Rajeshwari Nagar  3 BHK     1530.0   3.0      2.0
2608            Banashankari  4 BHK     2400.0   3.0      2.0
9635              Kanakapura  2 BHK     1017.0   2.0      1.0
...                      ...    ...        ...   ...      ...
11964               Varanasi  5 BHK     1200.0   4.0      1.0
5191                  Kogilu  3 BHK     1559.0   3.0      2.0
5390        Garudachar Palya  2 BHK     1060.0   2.0      1.0
860    Raja Rajeshwari Nagar  6 BHK     1200.0   4.0      2.0
7270   Silver Springs Layout  3 BHK     1885.0   3.0      3.0

[10656 rows x 5 columns]

In [61]:
Y_train

3411      90000.0
9142     111000.0
1971      57000.0
2608     370000.0
9635      66000.0
           ...   
11964     99000.0
5191     120000.0
5390      48500.0
860      125000.0
7270      90000.0
Name: price, Length: 10656, dtype: float64

In [62]:
Y_pred_rf

array([45938.        , 98120.        , 62833.33333333, ...,
       95200.        , 48100.        , 99800.        ])

In [63]:
r2_rfr = r2_score(Y_test, Y_pred_rf)

In [64]:
print(f'R-squared score: {r2_rfr}')

R-squared score: 0.6331195554647637


In [67]:
pickle.dump(pipeline, open('randomForestmodel.pkl','wb'))